print('www.netacad.com'.replace('netacad.com', "pythoninstitute.org"))
print('This is a good student'.replace('student', 'farmer'))
print('Apple juice'.replace('juice', ''))
print("This is it!".replace("is", "are", 1))
print('Banana is sweet'.replace('na', 'NA', 1))
print('Banana is sweet'.replace('na', 'NA', 2))
print('Banananana is sweet'.replace('na', 'NA', 3))