print('omega'.startswith('meg'))
print('omega'.startswith('om'))
print('Omega'.startswith('ome'))
print('omega'.startswith('omega'))
print('Saheed'.startswith('Saheed'))
print('**********')
print('[' + '   aleph   '.strip() + ']')