print('I know that I Know nothing.'.swapcase())
print('I know that I know nothing.'.title())
print('I know that I know nothing.'.upper())
print('I know that I know nothing.'.isupper())
print('I love python and i like i django'.swapcase())