f = open('xyz.txt', 'r')
print('File Name: {}'.format(f.name))
print('File Mode: {}'.format(f.mode))
print('Is File Readable: {}'.format(f.readable()))
print('Is File Writable: {}'.format(f.writable()))

print('****************')
f = open('../xyz.txt', 'w')
print('File Name: {}'.format(f.name))
print('File Mode: {}'.format(f.mode))
print('Is File Readable: {}'.format(f.readable()))
print('Is File Writable: {}'.format(f.writable()))

print('****************')
f = open('../xyz.txt', 'a')
print('File Name: {}'.format(f.name))
print('File Mode: {}'.format(f.mode))
print('Is File Readable: {}'.format(f.readable()))
print('Is File Writable: {}'.format(f.writable()))
