# Generated by Django 3.2.6 on 2022-08-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('math', models.IntegerField()),
                ('chem', models.IntegerField()),
                ('phy', models.IntegerField()),
                ('bio', models.IntegerField()),
                ('td', models.IntegerField()),
                ('eng', models.IntegerField()),
            ],
        ),
    ]
