print(len('alpha') < len('alphabet'))
print(len('alpha') < len('Alphabet'))
print(len('alpha') < len('Alphabet'.swapcase()))
print(len('alpha') < len('alphabet'.swapcase()))
print(len('ALPHABET') < len('alpha'))
#print(len(123) == len('123'))
#print(len(123) < len('123'))
#print(len(123))
print(len(' 1 23'))
print(len('beta') > len('Beta'))
print(len('beta') > len('beta'.swapcase()))
print(len('beta') > len('BETA'))
print(len('Beta'))
print(len('beta'))
print('beta' > 'Beta')
print('alpha' < 'alphabet')