q = []
q.append((1, 'Cake'))
q.append((5, 'Cup'))
q.append((2, 'Car'))
q.append((15, 'Sugar'))
q.append((1, 'Apple'))
q.append((6, 'Phone'))
q.sort(reverse=True)
print(q)
q.sort()
print(q)
print(q.pop(0))
print(q.pop(0))
print(q)
