queue = []
queue.append(10)
print(queue)
queue.append(30)
queue.append(20)
print(queue)
print(queue.pop(0))
print(queue)
print(queue.pop(1))
print(queue)
print(queue.pop(2))
print(queue)
print(queue.pop())
print(queue)