import collections
stack = collections.deque()
print(stack)
stack.append(10)
stack.append(20)
stack.append(30)
stack.append(40)
stack.append(50)
print(stack)
stack.popleft()
print(stack)
stack.pop()
stack.pop()
print(stack)
stack.pop()
stack.pop()
print(stack)
stack.pop()
#print(stack)
print(not stack) # True
print(len(stack))